theme: jekyll-theme-primer
title: LendingClub
description: Lending Club Data-Driven Investing
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
